### ISSUE TITLE
TODOs from file doesn't show up correctly

### ISSUE THREAD

**Issue by ItsDrike** [fabiospampinato/vscode-todo-plus#276]
## Description

When I go to the TODO tab and look at **Files** category it only shows sections even though I've got many TODOs in them in `TODO` file in the root of the project.

I also see this error whenever I start vscode in that repository:
![image](https://user-images.githubusercontent.com/20902250/87998705-f5a2aa80-caf8-11ea-9d99-d1cb65ed24ce.png)

<details>
<summary>
This is that error in the console:
</summary>
<p>

![image](https://user-images.githubusercontent.com/20902250/87998753-17039680-caf9-11ea-9584-086e7b29636e.png)

<details>
<summary>
This is that error in text form
</summary>
<p>

```
Error: [fabiospampinato.vscode-todo-plus]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api fabiospampinato.vscode-todo-plus
	at a (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:594)
	at Object.t.checkProposedApiEnabled (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:594)
	at m.getTooltip (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:611)
	at m.createTreeNode (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:611)
	at m.createAndRegisterTreeNode (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:610)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:609
	at processTicksAndRejections (/usr/lib/code/out/vs/code/electron-browser/workbench/internal/process/task_queues.js:85)
	at async Promise.all (/usr/lib/code/out/vs/code/electron-browser/workbench/index 2)
onDidChangeNotification @ /usr/lib/code/out/vs/workbench/workbench.desktop.main.js:2946
```

</p>
</details>
</p>
</details>

<details>
<summary>
This is my `TODO` file in the projects root
</summary>
<p>

![image](https://user-images.githubusercontent.com/20902250/87999105-2cc58b80-cafa-11ea-8823-906db9b4a687.png)

<details>
<summary>
In text
</summary>
<p>

```
Discuss:
  Theo:
    - Consider using `menus` for pagination instead of custom paginator
    - Global aiohttp session in bot is nice, but don't use `self.session = self.bot.aiosession` it doesn't make sense, simply use `self.bot.aiosession` directly
    - Solve issues with azure pipelines not checking branches and being unaccessible on master @today @critical
  Jana:
    - Rename `CORE DEV` discord role to `Core Devs` @low
    - **CodeFactor** detects TODOs in code as mistakes, that shouldn't be the case @today @high
      * Occured in PR #67

Todo:
  - Remove `manage_messages` restriction on the `ping` command in `bot/cogs/common.py` @1m
    Requested by Daneel (https://discordapp.com/channels/716612156975480832/728568693700689980/734868606935892019)
  - Use `ProcessedMember` in `bot/cogs/commands.py` inside of `userinfo` command @5m
  - Embed reset doesn't reset field IDs @30m
  - Use custom User -> Member convertion on `bot/cogs/games/tic_tac_toe.py` in `on_reaction_add`

  Code styling:
    - Rename all embeds in `bot/cogs/fun.py` to `embed` instead of `em` or `e` or something else @15m

  Pending (Tic Tac Toe):
    - Implement AI logic for Tic Tac Toe (`update-fun` branch, `bot/cogs/games/tic_tac_toe.py`) @2h
    - Use better embed format for Tic Tac Toe (`update-fun` branch, `bot/cogs/games/tic_tac_toe.py`) @10m
    ✔ Refactor Tic Tac Toe @est(2h) @started(20-07-20 23:30) @done(20-07-21 02:12) @lasted(2h42m27s)

```

</p>
</details>
</p>
</details>

Even though it shows the categories shouldn't it also show the individual tasks? Also, 2 nested categories from `Todo` category are missing, I'm not sure what's wrong here

## System and VSCode Details

![image](https://user-images.githubusercontent.com/20902250/87999615-ae69e900-cafb-11ea-9680-697957a46f8f.png)

## Another error I've noticed

I've also noticed 1 more minor error where when I don't have anything under `Archive:` category it doesn't show anything in the `Files` tab at all, I'd appreciate it if there was some kind of descriptive error popup saying what's wrong or somehow displaying it even with categories without any items.
<details>
<summary>
The image of this can be seen here
</summary>
<p>

![image](https://user-images.githubusercontent.com/20902250/87998617-b83e1d00-caf8-11ea-860f-96fb11ad9174.png)
</p>
</details>
